"""
Django settings for Config project.

Generated by 'django-admin startproject' using Django 4.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
import os
import re

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-73y$_38dtj2vih_vr7d_(m&3v=#(06tl$*7yvafpi!_2)_p8o5'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

AUTH_USER_MODEL = "User.User"

# for Access User Profile example(profile = request.user.get_profile())
AUTH_PROFILE_MODULE = "User.Profile"

ALLOWED_HOSTS = [
    "*",
    "localhost",
    "127.0.0.1",
    "herokuapp.com",
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000"
]

CORS_ALLOW_CREDENTIALS = True

# Application definition
THIRD_LIBRARIES= [
    'rest_framework', # Django rest framework (drf)
    'rest_framework.authtoken', # Adding token based authentication from drf
    'django_rest_passwordreset',
    # 'sslserver',
    'django_filters',
    'corsheaders',
]

MY_APP= [
    "Utils",
    "Language",
    "Category",
    "Payment",
    "Address",
    "User",
    "Restaurant",
    "Meal",
    "Driver",
    "Order",
    "Notification",
    "API",
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    ## Libraries
    *THIRD_LIBRARIES,
    ## My Apps
    *MY_APP,
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # for Langauge
    'django.middleware.locale.LocaleMiddleware',
    # for corsheaders
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'Config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, "templates"),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',
            ],
        },
    },
]

WSGI_APPLICATION = 'Config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases


DATABASE_DIR=os.path.join(BASE_DIR, "DataBase", 'db.sqlite3')

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME':  DATABASE_DIR,
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

LANGUAGES = [
    ("en", _("English")),
    ("ar", _("Arabic")),
    ("fr", _("French")),
]
# True for right-to-left languages like Arabic, and to False otherwise
# LANGUAGE_BIDI = False
# Languages using BiDi (right-to-left) layout
LANGUAGES_BIDI = [
    "ar",
    # "he", "ar-dz", "fa", "ur"
]

# LOCALE_PATHS = (BASE_DIR / "locale/",)
LOCALE_PATHS = [
    os.path.join(BASE_DIR, "Locales"),
    # '/home/www/project/common_files/locale',
    # '/var/local/translations/locale',
]


INTERNAL_IPS = [
    "127.0.0.1",
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static"),
)

STATICFILES_FINDERS = (
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
)

MEDIA_URL = "/media/"

MEDIA_ROOT = os.path.join(BASE_DIR, "media")
# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

####
ADMINS = (
    ('Shady', 'shadyelnady@gmail.com'),
)

MANAGERS = ADMINS

EXTERNAL_USER = "Shady"


CURRENCIES = (
    'USD',
    'EUR',
)
CURRENCY_CHOICES = [
    ('USD', 'USD $'),
    ('EUR', 'EUR €'),
]

DEFAULT_CURRENCY="EG"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    'DEFAULT_PERMISSION_CLASSES': [
        # 'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly',
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication'
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
    'ORDERING_PARAM': 'sorters[0][field]',
    # 'EXCEPTION_HANDLER': 'API.exceptions.django_error_handler'  ## Excepitions

}


# ## Twilio
# ACCOUNT_SID='AC581b79873a392165b31f7429d2fcfcfb'
# AUTH_TOKEN='d5c961c16b402d455d56e0930cfe6bfa'
# COUNTRY_CODE='+2'
# TWILIO_WHATSAPP_NUMBER='whatsapp:+14155238886'
# TWILIO_PHONE_NUMBER='+12525184301'
# TWILIO_PHONE_NUMBER='+13156673957'

##
# ## Twilio
# ACCOUNT_SID='ACab16021d54dc03acd45e5640f84aaf17'
# AUTH_TOKEN='0ee3a5fbd375483bd57db53c4f867592'
# COUNTRY_CODE='+2'
# TWILIO_WHATSAPP_NUMBER='whatsapp:+14155238886'
# # TWILIO_PHONE_NUMBER='+12525184301'
# # TWILIO_PHONE_NUMBER='+13156673957'
# TWILIO_PHONE_NUMBER='+14155238886'

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
)


##
LOGIN_URL = reverse_lazy('User:LogIn')
LOGIN_REDIRECT_URL = reverse_lazy('Restaurant:Intro')
LOGOUT_REDIRECT_URL = reverse_lazy('User:Splash')
LOGOUT_URL = reverse_lazy('User:LogOut')


## SMTP Configure
# Email Backend Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'  # Replace with your preferred backend

EMAIL_PORT = 587  # Replace with your email port
EMAIL_USE_TLS = True  # Set to False if your email server doesn't use TLS
EMAIL_HOST = 'smtp.gmail.com'  # Replace with your email host for gmail -> 'smtp.gmail.com'
EMAIL_HOST_USER = 'shadyelnady.gmail.co'  # Replace with your email username
EMAIL_HOST_PASSWORD = 'whbkjiyrbflyhlnr'  # Replace with your email password
# DEFAULT_FROM_EMAIL = 'shadyelnady.gmail.com'
EMAIL_USE_SSL = False

"""
    from django.conf import settings
    from django.core.mail import EmailMultiAlternatives
    emailFrom = [settings.EMAIL_HOST_USER]
        emailTo ='ponnamnarasimha1@gmail.com'
        text_content = 'Your content here'
        email_subject = "Subject here"
        msg = EmailMultiAlternatives(email_subject, text_content, emailFrom, [emailTo], )
        msg.send()
        return HttpResponse('We have sent a email verification please check your email')
"""