# Generated by Django 4.2.1 on 2023-05-26 22:17

import Utils.models
import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Address', '0001_initial'),
        ('Meal', '0001_initial'),
        ('Payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('color', colorfield.fields.ColorField(default=8, image_field=None, max_length=18, samples=None, unique=True, verbose_name='Color')),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colors',
            },
        ),
        migrations.CreateModel(
            name='ColorStep',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.FloatField(blank=True, null=True, verbose_name='Step')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Restaurant.color', verbose_name='Color')),
            ],
            options={
                'verbose_name': 'Color Step',
                'verbose_name_plural': 'Colors Steps',
            },
        ),
        migrations.CreateModel(
            name='Hospitality',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Date')),
                ('last_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Update')),
                ('name', models.CharField(max_length=15, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Hospitality',
                'verbose_name_plural': 'Hospitalities',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Date')),
                ('last_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Update')),
                ('name', models.CharField(max_length=15, verbose_name='Name')),
                ('free_shipping', models.FloatField(verbose_name='Free shipping')),
                ('type', models.CharField(choices=[('C', 'Coffee'), ('F', 'Fast Food')], max_length=2, verbose_name='Restaurant Type')),
                ('open_time', models.TimeField(blank=True, null=True, verbose_name='Open Time')),
                ('close_time', models.TimeField(blank=True, null=True, verbose_name='Close Time')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Restaurants', to='Address.address', verbose_name='Address')),
                ('hospitalities', models.ManyToManyField(related_name='+', to='Restaurant.hospitality', verbose_name='Hospitalities')),
            ],
            options={
                'verbose_name': 'Restaurant',
                'verbose_name_plural': 'Restaurants',
            },
        ),
        migrations.CreateModel(
            name='RestaurantMeal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Date')),
                ('last_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Update')),
                ('name', models.CharField(max_length=15, verbose_name='Name')),
                ('orders_count', models.SmallIntegerField(blank=True, editable=False, null=True, verbose_name='Order Count')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Restaurants', to='Meal.meal', verbose_name='Meal')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Restaurant_Meals', to='Meal.meal', verbose_name='Restaurant')),
            ],
            options={
                'verbose_name': 'Restaurant Meal',
                'verbose_name_plural': 'Restaurants Meals',
                'ordering': ['last_updated'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantMealSize',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Date')),
                ('last_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Update')),
                ('size', models.CharField(choices=[('L', 'L'), ('M', 'M'), ('S', 'S')], max_length=2, verbose_name='Size')),
                ('price', models.FloatField(verbose_name='Price')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Meals+', to='Payment.currency', verbose_name='Currency')),
                ('restaurant_Meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Restaurant_Meals_Sizes', to='Restaurant.restaurantmeal', verbose_name='Restaurant Meal')),
            ],
            options={
                'verbose_name': 'Restaurant Meal Size',
                'verbose_name_plural': 'Restaurants Meals Sizes',
            },
        ),
        migrations.CreateModel(
            name='RestaurantMealImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default="images/{instance.__class__.__name__}/default.jpg' %}", null=True, upload_to=Utils.models.upload_to, verbose_name='Image')),
                ('restaurant_meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Images', to='Restaurant.restaurantmeal', verbose_name='Restaurant Meal')),
            ],
            options={
                'verbose_name': 'Restaurant Meal Image',
                'verbose_name_plural': 'Restaurant Meals Images',
            },
        ),
        migrations.CreateModel(
            name='Gradient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('gradient_type', models.CharField(blank=True, choices=[('LG', 'LinearGradient')], max_length=2, null=True, verbose_name='Gradient Type')),
                ('begin', models.CharField(blank=True, choices=[('TR', 'topRight'), ('BL', 'bottomLeft'), ('BR', 'bottomRight'), ('TL', 'topRight')], max_length=2, null=True, verbose_name='Begin')),
                ('end', models.CharField(blank=True, choices=[('TR', 'topRight'), ('BL', 'bottomLeft'), ('BR', 'bottomRight'), ('TL', 'topRight')], max_length=2, null=True, verbose_name='End')),
                ('colors_steps', models.ManyToManyField(through='Restaurant.ColorStep', to='Restaurant.color', verbose_name='Colors Steps')),
            ],
            options={
                'verbose_name': 'Gradient',
                'verbose_name_plural': 'Gradients',
            },
        ),
        migrations.AddField(
            model_name='colorstep',
            name='gradient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurant.gradient', verbose_name='Gradient'),
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('image', models.ImageField(blank=True, default="images/{instance.__class__.__name__}/default.jpg' %}", null=True, upload_to=Utils.models.upload_to, verbose_name='Image')),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='Logo', serialize=False, to='Restaurant.restaurant', verbose_name='Restaurant')),
                ('gradient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Logos', to='Restaurant.gradient', verbose_name='Gradient')),
            ],
            options={
                'verbose_name': 'Logo',
                'verbose_name_plural': 'Logos',
            },
        ),
    ]
