# Generated by Django 4.2.1 on 2023-05-22 02:20

import Utils.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Payment', '0001_initial'),
        ('Location', '0001_initial'),
        ('Meal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Date')),
                ('last_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Update')),
                ('name', models.CharField(max_length=15, unique=True, verbose_name='Name')),
                ('is_best', models.BooleanField(default=False, verbose_name='is Best')),
                ('free_shipping', models.FloatField(verbose_name='Free shipping')),
                ('type', models.CharField(choices=[('C', 'Coffee'), ('F', 'Fast Food')], max_length=2, verbose_name='Restaurant Type')),
                ('open_time', models.TimeField(verbose_name='Open Time')),
                ('close_time', models.TimeField(verbose_name='Close Time')),
                ('is_nearby', models.BooleanField(default=False, verbose_name='is Nearby')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Profiles', to='Location.location', verbose_name='Location')),
            ],
            options={
                'verbose_name': 'Restaurant',
                'verbose_name_plural': 'Restaurants',
            },
        ),
        migrations.CreateModel(
            name='RestaurantMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_popular', models.BooleanField(default=False, verbose_name='is Popular')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Restaurants', to='Meal.meal', verbose_name='Meal')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Restaurant_Meals', to='Meal.meal', verbose_name='Restaurant')),
            ],
            options={
                'verbose_name': 'Restaurant Meal',
                'verbose_name_plural': 'Restaurants Meals',
                'unique_together': {('restaurant', 'meal')},
            },
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('image', models.ImageField(blank=True, default="images/{instance.__class__.__name__}/default.jpg' %}", null=True, upload_to=Utils.models.upload_to, verbose_name='Image')),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='Logo', serialize=False, to='Restaurant.restaurant', verbose_name='Restaurant')),
                ('gradient_type', models.CharField(blank=True, choices=[('LG', 'LinearGradient')], max_length=2, null=True, verbose_name='Gradient Type')),
                ('begin', models.CharField(blank=True, choices=[('TR', 'topRight'), ('BL', 'bottomLeft'), ('BR', 'bottomRight'), ('TL', 'topRight')], max_length=2, null=True, verbose_name='Begin')),
                ('end', models.CharField(blank=True, choices=[('TR', 'topRight'), ('BL', 'bottomLeft'), ('BR', 'bottomRight'), ('TL', 'topRight')], max_length=2, null=True, verbose_name='End')),
            ],
            options={
                'verbose_name': 'Logo',
                'verbose_name_plural': 'Logos',
            },
        ),
        migrations.CreateModel(
            name='RestaurantMealSize',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Date')),
                ('last_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Update')),
                ('size', models.CharField(choices=[('L', 'L'), ('M', 'M'), ('S', 'S')], max_length=2, verbose_name='Size')),
                ('price', models.FloatField(verbose_name='Price')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Meals+', to='Payment.currency', verbose_name='Currency')),
                ('restaurant_Meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Restaurant_Meals_Sizes', to='Restaurant.restaurantmeal', verbose_name='Restaurant Meal')),
            ],
            options={
                'verbose_name': 'Restaurant Meal Size',
                'verbose_name_plural': 'Restaurants Meals Sizes',
            },
        ),
        migrations.CreateModel(
            name='RestaurantMealImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default="images/{instance.__class__.__name__}/default.jpg' %}", null=True, upload_to=Utils.models.upload_to, verbose_name='Image')),
                ('restaurant_meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Images', to='Restaurant.restaurantmeal', verbose_name='Restaurant Meal')),
            ],
            options={
                'verbose_name': 'Restaurant Meal Image',
                'verbose_name_plural': 'Restaurant Meals Images',
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.FloatField(verbose_name='Step')),
                ('logo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Steps', to='Restaurant.logo', verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'Step',
                'verbose_name_plural': 'Steps',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=2, verbose_name='Color')),
                ('logo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Colors', to='Restaurant.logo', verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colors',
            },
        ),
    ]
