# Generated by Django 4.2.1 on 2023-05-22 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.FloatField(blank=True, null=True, verbose_name='Step')),
            ],
            options={
                'verbose_name': 'Color Step',
                'verbose_name_plural': 'Colors Steps',
            },
        ),
        migrations.CreateModel(
            name='Gradient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gradient_type', models.CharField(blank=True, choices=[('LG', 'LinearGradient')], max_length=2, null=True, verbose_name='Gradient Type')),
                ('begin', models.CharField(blank=True, choices=[('TR', 'topRight'), ('BL', 'bottomLeft'), ('BR', 'bottomRight'), ('TL', 'topRight')], max_length=2, null=True, verbose_name='Begin')),
                ('end', models.CharField(blank=True, choices=[('TR', 'topRight'), ('BL', 'bottomLeft'), ('BR', 'bottomRight'), ('TL', 'topRight')], max_length=2, null=True, verbose_name='End')),
            ],
            options={
                'verbose_name': 'Gradient',
                'verbose_name_plural': 'Gradients',
            },
        ),
        migrations.RemoveField(
            model_name='color',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='logo',
            name='begin',
        ),
        migrations.RemoveField(
            model_name='logo',
            name='end',
        ),
        migrations.RemoveField(
            model_name='logo',
            name='gradient_type',
        ),
        migrations.AddField(
            model_name='logo',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Logos', to='Restaurant.color', verbose_name='Color'),
        ),
        migrations.DeleteModel(
            name='Step',
        ),
        migrations.AddField(
            model_name='gradient',
            name='colors_steps',
            field=models.ManyToManyField(through='Restaurant.ColorStep', to='Restaurant.color', verbose_name='Colors Steps'),
        ),
        migrations.AddField(
            model_name='colorstep',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Restaurant.color', verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='colorstep',
            name='gradient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurant.gradient', verbose_name='Gradient'),
        ),
        migrations.AddField(
            model_name='logo',
            name='gradient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Logos', to='Restaurant.gradient', verbose_name='Gradient'),
        ),
    ]
