# Generated by Django 4.2.1 on 2023-05-22 05:31

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0002_colorstep_gradient_remove_color_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='color',
            field=colorfield.fields.ColorField(default=8, image_field=None, max_length=18, samples=[('#FFFFFF', 'white'), ('#000000', 'black')], verbose_name='Color'),
        ),
    ]
