# Generated by Django 4.2.1 on 2023-05-22 05:49

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0003_alter_color_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='color',
            field=colorfield.fields.ColorField(default=8, image_field=None, max_length=18, samples=None, verbose_name='Color'),
        ),
    ]
