# Generated by Django 4.2.1 on 2023-05-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_remove_profile_otp_remove_profile_uid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='otp_base32',
            new_name='otp',
        ),
        migrations.RemoveField(
            model_name='user',
            name='otp_auth_url',
        ),
        migrations.RemoveField(
            model_name='user',
            name='otp_verified',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'E-Mail Is User'}, max_length=200, unique=True, verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'User Name Is User. choose Another'}, max_length=30, unique=True, verbose_name='User Name'),
        ),
    ]
