# Generated by Django 4.2.1 on 2023-05-22 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Payment', '0001_initial'),
        ('Driver', '0001_initial'),
        ('Restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Date')),
                ('last_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Update')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Orders', to='Payment.paymentmethod', verbose_name='Payment Method')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='OrderRateRestaurant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Date')),
                ('last_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Update')),
                ('reviews', models.FloatField(verbose_name='Reviews')),
                ('comment', models.TextField(max_length=500, verbose_name='Comment')),
                ('is_good_package', models.BooleanField(verbose_name='is Good package')),
                ('is_clean', models.BooleanField(verbose_name='is Clean')),
                ('is_pair_price', models.BooleanField(verbose_name='is pair_price')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Order_Rate_Restaurant', to='Order.order', verbose_name='Order')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Orders', to='Restaurant.restaurant', verbose_name='Restaurant')),
            ],
            options={
                'verbose_name': 'Order Rate Restaurant',
                'verbose_name_plural': 'Orders Rate Restaurants',
            },
        ),
        migrations.CreateModel(
            name='OrderRateDriver',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Date')),
                ('last_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Update')),
                ('reviews', models.FloatField(verbose_name='Reviews')),
                ('comment', models.TextField(max_length=200, verbose_name='Comment')),
                ('is_good_service', models.BooleanField(verbose_name='is Good Service')),
                ('is_on_time', models.BooleanField(verbose_name='is On Time')),
                ('is_clean', models.BooleanField(verbose_name='is Clean')),
                ('is_carefull', models.BooleanField(verbose_name='is Carefull')),
                ('is_work_hard', models.BooleanField(verbose_name='is Work Hard')),
                ('is_polite', models.BooleanField(verbose_name='is Polite')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Orders', to='Driver.driver', verbose_name='Driver')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Order_Rate_Driver', to='Order.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Order Rate Driver',
                'verbose_name_plural': 'Orders Rate Drivers',
            },
        ),
        migrations.CreateModel(
            name='OrderMeal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Date')),
                ('last_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Update')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Quantity')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Orders', to='Restaurant.restaurantmealsize', verbose_name='Meal')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Order_Meals', to='Order.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Order Meal',
                'verbose_name_plural': 'Orders Meals',
            },
        ),
    ]
