# Generated by Django 4.2.1 on 2023-05-26 22:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Order', '0001_initial'),
        ('Payment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Orders', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Orders', to='Payment.paymentmethod', verbose_name='Payment Method'),
        ),
        migrations.AlterUniqueTogether(
            name='orderraterestaurant',
            unique_together={('order', 'restaurant')},
        ),
        migrations.AlterUniqueTogether(
            name='orderratedriver',
            unique_together={('order', 'driver')},
        ),
        migrations.AlterUniqueTogether(
            name='ordermeal',
            unique_together={('order', 'meal')},
        ),
    ]
